# Generated by Django 2.2.12 on 2020-05-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pediatrician_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pediatrician_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, max_length=240, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQ', 'Requested'), ('SEN', 'Sent')], default='REQ', max_length=3)),
                ('appointment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointments.AppointmentRequest')),
            ],
        ),
    ]
