# Generated by Django 2.2.12 on 2020-05-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REQ', 'Solicitada'), ('SNT', 'Enviada')], default='REQ', max_length=3),
        ),
    ]
